blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/codeldev/livewire-markdown-editor/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/codeldev/livewire-markdown-editor/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/codeldev/livewire-markdown-editor/security/policy
    about: Learn how to notify me for sensitive bugs
